name: Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true            
      - uses: docker/setup-buildx-action@v1  
      - name: set lower case repo name
        run: |
          echo "REPO_LC=`echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'`"  >>${GITHUB_ENV}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:2.20.2



